# Generated by Django 4.2.16 on 2024-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0013_range_excluded_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="parents_only",
            field=models.BooleanField(default=False),
        ),
    ]
