# Generated by Django 4.2.16 on 2024-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_alter_line_num_allocated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "orders",
                    models.ManyToManyField(blank=True, null=True, to="order.order"),
                ),
            ],
        ),
    ]
