# Generated by Django 4.2.16 on 2024-10-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offer", "0015_alter_range_parents_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "required_amount",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Required Amount"
                    ),
                ),
                (
                    "price_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Price threshold",
                    ),
                ),
                (
                    "show_price_progress_bar",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                ("cart_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "contained_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contained_range",
                        to="offer.range",
                        verbose_name="Contained products",
                    ),
                ),
                (
                    "excluded_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excluded_range",
                        to="offer.range",
                        verbose_name="Excluded products",
                    ),
                ),
                (
                    "included_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="included_range",
                        to="offer.range",
                        verbose_name="Included products",
                    ),
                ),
                (
                    "promo_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_range",
                        to="offer.range",
                        verbose_name="Promo products",
                    ),
                ),
            ],
        ),
    ]
