# Generated by Django 4.2.16 on 2024-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_favorite_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="display_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
