# Generated by Django 4.2.16 on 2024-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0033_alter_productcategory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="selected_subcategories",
            field=models.ManyToManyField(blank=True, to="catalogue.category"),
        ),
    ]
